import Header from "@/components/Header";
import { supabaseAdmin } from "@/lib/supabase";
import { notFound } from "next/navigation";

export default async function ReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  const { data, error } = await supabaseAdmin
    .from("reports")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  console.log("REPORT ID:", id);
  console.log("SUPABASE DATA:", data);
  console.log("SUPABASE ERROR:", error);

  if (error || !data) notFound();

  return (
    <div className="auditPage">
      <Header simple />

      <main className="reportPage">
        <div className="reportCard">
          <span className="reportBadge">Unlocked Full Report</span>

          <h1 className="reportTitle">
            Your Personalised Savings Report
          </h1>

          <p className="reportSub">
            Generated by SpendShift AI based on your audit responses.
          </p>

          <div className="reportContent">
            {data.report}
          </div>
        </div>
      </main>
    </div>
  );
}